### ISSUE TITLE
Issue waiting for crew

### ISSUE THREAD

**Issue by TheRealMrKam** [Sylkadi/BrutalCompanyMinus#21]
Hello i have an error with BCM, he seem to try to generate enemy and scrap, while i disabled that in the config, it goes like this in console:  
- [Info   :BrutalCompanyMinus] Generating Enemy + Scrap rarity config

and after that there is an error.

settings 
- Generate and use enemy weights? = false                    
- Generate and use scrap weights? = false
 
 Here is the log :
[LogOutput.log](https://github.com/Sylkadi/BrutalCompanyMinus/files/14352751/LogOutput.log)

Also have other errors that say this could cause a issue before !

**Comment by Sylkadi** [comment]
There should an _Enable config option, when I get home I'll test this my self.

**Comment by Sylkadi** [comment]
Give me the code to the modpack, pls

![Screenshot_148](https://github.com/Sylkadi/BrutalCompanyMinus/assets/101504347/50884eb7-288c-451e-bbcb-8d42ef1d5c6b)

**Comment by TheRealMrKam** [comment]
I don't use Thunderstore mod manager :/
Can i give you the modlist ? but will be a pain...

What should i do ?

**Comment by Sylkadi** [comment]
modlist is good enough

**Comment by TheRealMrKam** [comment]
Yeah but i have way too many mods so... yeah

Anyways here it is : 
[Mods.log](https://github.com/Sylkadi/BrutalCompanyMinus/files/14365293/Mods.log)

**Comment by Sylkadi** [comment]
Why did i ask for mod list when it's in the original log file you sent... anyways

**Comment by TheRealMrKam** [comment]
Haha, well... true
The bug doesn't happen  everytime, maybe it's due to a particular event or something
Here is my BCM config if you need it:
[BrutalCompanyMinus.zip](https://github.com/Sylkadi/BrutalCompanyMinus/files/14365593/BrutalCompanyMinus.zip)

Edit: Maybe it's better to take the modlist in the first log i sended you i may have added/deleted some mods in between the time passed

**Comment by Sylkadi** [comment]
This should be fixed in next release, whenever i decide to update. Problem was that dictionaries aren't thread safe.

**Comment by TheRealMrKam** [comment]
Thank you ! :)

(ps: I don't know what "dictionaries aren't thread safe" is, was it conflicting with one of my mods ?)

**Comment by TheRealMrKam** [comment]
It's still stuck on Waiting for crew after the update. 

Seem to be an error with the mod LaserControl, but i disabled it and still have a different error with BCM.

logs with lasercontrol :
[LogOutput.log](https://github.com/Sylkadi/BrutalCompanyMinus/files/14380786/LogOutput.log)

logs without lasercontrol: 
[LogOutput.log](https://github.com/Sylkadi/BrutalCompanyMinus/files/14380772/LogOutput.log)

**Comment by Sylkadi** [comment]
You can disable the mod from generating custom weights in Enemy_Scrap_Weights config which should stop it from breaking, my only idea as to why it's breaking is that there is a null entry in the level list other than that idk.

**Comment by TheRealMrKam** [comment]
Oh my bad didn't check the configs, but they are empty (exept difficulty settings and events but most events are gone and new ones are there.)


![image](https://github.com/Sylkadi/BrutalCompanyMinus/assets/154998012/808a8175-471f-4600-9f42-804ab66788d2)
